"""L2 scenario storage — groups related atomic memories into summarized blocks.

Scenarios are generated by an LLM (see MemoryManager.consolidate_scenarios)
and stored in the same SQLite database as memories. Each memory belongs to
at most one scenario via the memories.scenario_id column (added here by
migration). Scenario summaries carry their own embedding so they participate
in semantic recall alongside atomic memories.
"""

from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass, field
from typing import Any

from ..rag._store_utils import cosine_similarity as _cosine_similarity
from .memory_store import Memory

_LOGGER = logging.getLogger(__name__)

# Recall defaults for scenario search
SCENARIO_RECALL_TOP_K = 2
SCENARIO_RECALL_MIN_SIMILARITY = 0.4


@dataclass
class Scenario:
    """A summarized block of related memories (L2 layer)."""

    id: str
    user_id: str
    title: str
    summary: str
    memory_count: int
    created_at: float
    updated_at: float
    score: float = 0.0  # Search relevance score (filled during search)


@dataclass
class ScenarioStore:
    """SQLite storage for L2 scenarios. Shares the RAG database connection."""

    store: Any  # SqliteStore — avoid circular import
    _tables_created: bool = field(default=False, repr=False)

    async def async_initialize(self) -> None:
        """Create scenario table and migrate memories.scenario_id column.

        Must run AFTER MemoryStore.async_initialize (memories table required).
        """
        if self._tables_created:
            return

        conn = self.store._conn
        if conn is None:
            raise RuntimeError("SqliteStore connection not available")

        cursor = conn.cursor()

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS memory_scenarios (
                id TEXT PRIMARY KEY,
                user_id TEXT NOT NULL,
                title TEXT NOT NULL,
                summary TEXT NOT NULL,
                embedding BLOB NOT NULL,
                memory_count INTEGER NOT NULL DEFAULT 0,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL
            )
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_scenarios_user_id
            ON memory_scenarios(user_id)
        """)

        # Migration: add scenario_id column to memories if missing
        try:
            cursor.execute("SELECT scenario_id FROM memories LIMIT 1")
        except Exception:
            _LOGGER.info("Migrating memories table: adding scenario_id column")
            cursor.execute("ALTER TABLE memories ADD COLUMN scenario_id TEXT")

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_memories_scenario
            ON memories(user_id, scenario_id)
        """)

        conn.commit()
        self._tables_created = True
        _LOGGER.info("Scenario store tables initialized")

    async def store_scenario(
        self,
        *,
        user_id: str,
        title: str,
        summary: str,
        embedding: list[float],
        memory_ids: list[str],
    ) -> str | None:
        """Insert a scenario and link member memories to it."""
        conn = self.store._conn
        if conn is None or not memory_ids:
            return None

        scenario_id = str(uuid.uuid4())
        now = time.time()
        embedding_blob = self.store._embedding_to_blob(embedding)

        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO memory_scenarios
                (id, user_id, title, summary, embedding, memory_count,
                 created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (scenario_id, user_id, title, summary, embedding_blob,
             len(memory_ids), now, now),
        )

        placeholders = ",".join("?" * len(memory_ids))
        cursor.execute(
            f"UPDATE memories SET scenario_id = ?, updated_at = ? "
            f"WHERE id IN ({placeholders}) AND user_id = ?",
            (scenario_id, now, *memory_ids, user_id),
        )

        conn.commit()
        return scenario_id

    async def search_scenarios(
        self,
        query_embedding: list[float],
        user_id: str,
        *,
        limit: int = SCENARIO_RECALL_TOP_K,
        min_similarity: float = SCENARIO_RECALL_MIN_SIMILARITY,
    ) -> list[Scenario]:
        """Vector search over scenario summaries (full scan + Python cosine)."""
        conn = self.store._conn
        if conn is None:
            return []

        cursor = conn.cursor()
        cursor.execute(
            "SELECT * FROM memory_scenarios WHERE user_id = ?", (user_id,)
        )
        rows = cursor.fetchall()

        results = []
        for row in rows:
            stored_embedding = self.store._read_embedding(row["embedding"])
            similarity = _cosine_similarity(query_embedding, stored_embedding)
            if similarity >= min_similarity:
                results.append(
                    Scenario(
                        id=row["id"],
                        user_id=row["user_id"],
                        title=row["title"],
                        summary=row["summary"],
                        memory_count=row["memory_count"],
                        created_at=row["created_at"],
                        updated_at=row["updated_at"],
                        score=similarity,
                    )
                )

        results.sort(key=lambda s: s.score, reverse=True)
        return results[:limit]

    async def list_ungrouped_memories(
        self, user_id: str, *, limit: int = 100
    ) -> list[Memory]:
        """Return non-expired memories not yet assigned to any scenario."""
        conn = self.store._conn
        if conn is None:
            return []

        now = time.time()
        cursor = conn.cursor()
        cursor.execute(
            "SELECT * FROM memories WHERE user_id = ? AND scenario_id IS NULL "
            "AND (expires_at IS NULL OR expires_at > ?) "
            "ORDER BY created_at ASC LIMIT ?",
            (user_id, now, limit),
        )
        rows = cursor.fetchall()
        return [
            Memory(
                id=row["id"],
                user_id=row["user_id"],
                text=row["text"],
                category=row["category"],
                importance=row["importance"],
                source=row["source"],
                session_id=row["session_id"],
                created_at=row["created_at"],
                updated_at=row["updated_at"],
                expires_at=row["expires_at"],
            )
            for row in rows
        ]

    async def count_scenarios(self, user_id: str) -> int:
        conn = self.store._conn
        if conn is None:
            return 0
        cursor = conn.cursor()
        cursor.execute(
            "SELECT COUNT(*) FROM memory_scenarios WHERE user_id = ?", (user_id,)
        )
        return cursor.fetchone()[0]

    async def delete_user_scenarios(self, user_id: str) -> int:
        """Delete all scenarios for a user; members return to ungrouped pool."""
        conn = self.store._conn
        if conn is None:
            return 0
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE memories SET scenario_id = NULL WHERE user_id = ?", (user_id,)
        )
        cursor.execute(
            "DELETE FROM memory_scenarios WHERE user_id = ?", (user_id,)
        )
        deleted = cursor.rowcount
        conn.commit()
        return deleted
